// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace AnirolacComponent.Samples.iOS
{
	public partial class ImageGalleryViewController : UIViewController
	{
		public ImageGalleryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
